name: Plugin Updater

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - webcomponents/**.js
      - webcomponents/**.ts
      - webcomponents/**.json
      - webcomponents/**.svelte

permissions:
  contents: write

jobs:
  build-webcomponents:
    name: Build web components
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Get version
        id: version
        run: |
          version=$(jq -r .version webcomponents/package.json)
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Build
        run: cd webcomponents && npm install && npm run build
      - name: Publish web components
        uses: softprops/action-gh-release@v2
        with:
          files: webcomponents/dist/flow-launcher-docs-web-components.js
          tag_name: webcomponents-v${{ steps.version.outputs.version }}
